samvera/hydra-pcdm

lib/hydra/pcdm.rb, lib/hydra/pcdm/models/collection.rb, lib/hydra/pcdm/models/object.rb
This makes it so that builds such as sufia have time to load their
dependencies before trying to require.
See https://travis-ci.org/projecthydra/sufia/jobs/61206708
=> Don't require aggregations until its used

.travis.yml
Don't build libxml2 and libxslt that are bundled with nokogiri
=> Use containerized builds to speed up travis.

lib/hydra/pcdm.rb
Fixes:
lib/hydra/pcdm.rb:1:in `<top (required)>': uninitialized constant
Hydra (NameError)
=> Define Hydra if it doesn't exist

lib/hydra/pcdm/models/collection.rb, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, lib/hydra/pcdm/models/object.rb
Otherwise if you're using the behaviors, e.g.:
```ruby
class Book < ActiveFedora::Base
include Hydra::PCDM::ObjectBehavior
end
```
You'll get:
```
NoMethodError: undefined method `aggregates' for Book:Class
```
=> Requrires in the files where they're needed

spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb
That functionality lives in ActiveFedora and Hyra::AccessControls.
We don't need to test for it here.
See #53 for further discussion of where ACLs belong.
=> Remove tests for descriptive and access metadata

README.md, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb
This primarily extends pcdm object tests to make them consistent with testing for pcdm collection.  This also added object hasMember object in the same way that collection hasMember collection.
=> add tests for better coverage of pcdm objects

README.md
trivial change to README to fix coverage badge to show master branch coverage
=> set coverage badge to master branch

README.md, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb
Also removed pending tests that should be added when the functionality they are related to is added to the code base.  All removed items were either already addressed or have outstanding tickets.  There were a couple of TODOs that were not removed, but they are marked with the issue number that is addressing that TODO.
=> remove todo comments

lib/hydra/pcdm.rb, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/services/collection/add_collection.rb, lib/hydra/pcdm/services/collection/add_object.rb, lib/hydra/pcdm/services/collection/add_related_object.rb, lib/hydra/pcdm/services/collection/get_collections.rb, lib/hydra/pcdm/services/collection/get_objects.rb, lib/hydra/pcdm/services/collection/get_related_objects.rb, lib/hydra/pcdm/services/object/add_object.rb, lib/hydra/pcdm/services/object/add_related_object.rb, lib/hydra/pcdm/services/object/get_objects.rb, lib/hydra/pcdm/services/object/get_related_objects.rb, spec/hydra/pcdm/services/collection/add_collection_spec.rb, spec/hydra/pcdm/services/collection/add_object_spec.rb, spec/hydra/pcdm/services/collection/add_related_object_spec.rb, spec/hydra/pcdm/services/collection/get_collections_spec.rb, spec/hydra/pcdm/services/collection/get_objects_spec.rb, spec/hydra/pcdm/services/collection/get_related_objects_spec.rb, spec/hydra/pcdm/services/object/add_object_spec.rb, spec/hydra/pcdm/services/object/add_related_object_spec.rb, spec/hydra/pcdm/services/object/get_objects_spec.rb, spec/hydra/pcdm/services/object/get_related_objects_spec.rb
New Collection Services:
* AddCollectionToCollection
* AddObjectToCollection
* AddRelatedObjectToCollection
* GetCollectionsFromCollection
* GetObjectsFromCollection
* GetRelatedObjectsFromCollection
New Object Services:
* AddObjectToObject
* AddRelatedObjectToObject
* GetObjectsFromObject
* GetRelatedObjectsFromObject
=> new services for adding and getting

lib/hydra/pcdm.rb, lib/hydra/pcdm/services/collection/get_related_objects.rb, lib/hydra/pcdm/services/collection/remove_collection.rb, lib/hydra/pcdm/services/collection/remove_object.rb, lib/hydra/pcdm/services/collection/remove_related_object.rb, lib/hydra/pcdm/services/object/get_related_objects.rb, lib/hydra/pcdm/services/object/remove_object.rb, lib/hydra/pcdm/services/object/remove_related_object.rb, spec/hydra/pcdm/services/collection/add_collection_spec.rb, spec/hydra/pcdm/services/collection/add_related_object_spec.rb, spec/hydra/pcdm/services/collection/get_objects_spec.rb, spec/hydra/pcdm/services/collection/get_related_objects_spec.rb, spec/hydra/pcdm/services/collection/remove_collection_spec.rb, spec/hydra/pcdm/services/collection/remove_object_spec.rb, spec/hydra/pcdm/services/collection/remove_related_object_spec.rb, spec/hydra/pcdm/services/object/add_related_object_spec.rb, spec/hydra/pcdm/services/object/remove_object_spec.rb, spec/hydra/pcdm/services/object/remove_related_object_spec.rb
New Services:
* RemoveCollectionFromCollection
* RemoveObjectFromCollection
* RemoveRelatedObjectFromCollection
* RemoveObjectFromObject
* RemoveRelatedObjectFromObject
Updated Services:
* GetRelatedObjectsFromCollection - return array
* GetRelatedObjectsFromObject - return array
=> Add remove services for collections, objects, and related objects.

lib/hydra/pcdm.rb, lib/hydra/pcdm/collection_indexer.rb, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, lib/hydra/pcdm/object_indexer.rb, lib/hydra/pcdm/services/collection/get_collections.rb, spec/hydra/pcdm/collection_indexer_spec.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb, spec/hydra/pcdm/object_indexer_spec.rb, spec/hydra/pcdm/services/collection/add_collection_spec.rb, spec/hydra/pcdm/services/collection/add_object_spec.rb, spec/hydra/pcdm/services/collection/add_related_object_spec.rb, spec/hydra/pcdm/services/object/add_object_spec.rb, spec/hydra/pcdm/services/object/add_related_object_spec.rb
Collection#collections used to return collections that contained this
object (parent collections, see
https://github.com/projecthydra/hydra-collections/blob/master/lib/hydra/collections/collectible.rb#L10
) but now collections returns child collections.  This renaming hopes to
reverse the incompatible naming change.
=> Rename #collections to child_collections

README.md, lib/hydra/pcdm/vocab/pcdm_terms.rb
The PCDM wiki location has changed. This PR includes updated URL references.
=> update PCDM wiki location

spec/hydra/pcdm/models/object_spec.rb
The call to `content_changed?` in the call to `save` fails to persist an ActiveFedora File if the content of the File is nil.  Adding dummy contents to to the File in the tests allows to it to be persisted to fedora, and thus alleviates the 404 error that would have been returned on refresh.
=> Add content to mock File in object spec.

lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb
Fix by checking objects instead of ids.
=> fix ancestor? fails when ids are nil by checking objects instead

spec/hydra/pcdm/services/collection/add_object_spec.rb, spec/hydra/pcdm/services/object/add_object_spec.rb
changes to tests to improve execution time
* collapse first 4 tests into one that covers several use cases while avoiding duplicate setups
* for validation tests, create objects only once
* do not save unless absolutely necessary
* use new instead of create (effectively working with objects in memory as they are not saved to Fedora)
Impact:
before - 15s
after - 0.2s
This is almost exclusively accounted for by the use of new instead of create.
=> optimize collection/add_object_spec object/add_object_spec

lib/hydra/pcdm/models/concerns/child_objects.rb
This is no longer needed because it's implemented by the filter associations.
=> Remove child_object_ids method.

Gemfile, lib/hydra/pcdm/collection_indexer.rb, lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, lib/hydra/pcdm/models/concerns/pcdm_behavior.rb, lib/hydra/pcdm/object_indexer.rb, spec/hydra/pcdm/collection_indexer_spec.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb, spec/hydra/pcdm/object_indexer_spec.rb
There are a few questions here for me:
1. This assumes #objects/#collections returns those objects and collections which are ORDERED underneath. Is that a bad assumption? Should there be #objects AND #ordered_objects? (Not looking forward to that, but whatcha gonna do)
2. Deleting is different here - you can't just do ordered_members.delete(member), because that member can appear in the ordering multiple times. So I'm using delete_at in the specs - should there be something different?
=> New ordering

lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/models/concerns/object_behavior.rb, lib/hydra/pcdm/models/concerns/pcdm_behavior.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/models/object_spec.rb, spec/spec_helper.rb
Fixes projecthydra-labs/hydra-works#258
Also, remove all deprecations (four months overdue).
=> ObjectBehavior#in_objects should return parent objects whether members are added via `members.<<` or `ordered_members.<<`

lib/hydra/pcdm/services/file/add_type.rb, lib/hydra/pcdm/services/file/get_mime_type.rb
Instead of a class which you can instantiate, favoring a module which
cannot be instantiated. This narrows the interface of the constant.
=> Favoring module over class for service methods

lib/hydra/pcdm.rb, lib/hydra/pcdm/collection_indexer.rb, lib/hydra/pcdm/config.rb, lib/hydra/pcdm/models/concerns/pcdm_behavior.rb, lib/hydra/pcdm/object_indexer.rb, spec/hydra/pcdm/collection_indexer_spec.rb, spec/hydra/pcdm/config_spec.rb, spec/hydra/pcdm/object_indexer_spec.rb
Favoring a method over magic string as this allows future
configuration. It is perhaps a bit deceptive to name this Config as it
doesn't expose a configure option. However that is something for a
future concern.
Configuration container options:
* https://github.com/dry-rb/dry-configuration
* ActiveSupport::Configurable
Closes #189
=> Extracting methods for index key names

lib/hydra/pcdm/models/concerns/object_behavior.rb
Unless there is code accessing the specific class instance variable,
memoization of a constant does not add to any improved performance.
Instead just a bit more memory is required.
Closes #212
=> Removing memoization of a constant

lib/hydra/pcdm/models/concerns/collection_behavior.rb, lib/hydra/pcdm/validators.rb, lib/hydra/pcdm/validators/pcdm_collection_validator.rb
This validator does nothing more than return true. The overall design
goal is to return a meaningful object with the method call. By
returning `nil` we expect the upstream message sender to jump through
a bit of logic that is analogue to the following:
```ruby
type_validator = Collection.type_validator
if type_validator
type_validator.validate!(*args)
end
```
Instead, with a type validator that implements a common interface the
message sender can do the following with far greater confidence:
```ruby
Collection.type_validator.validate!(*args)
```
Closes #214
=> Adding a PCDMCollectionValidator

lib/hydra/pcdm/models/concerns/object_behavior.rb
Had reversed proxyFor and proxyIn, which works for Fedora, but causes problems for AF.
Keeping them the same as the other indirect containers (where proxyFor points to the remote object) works for both hydra-pcdm and AF, and is more correct usage of ORE Proxy, too.
=> Fixing proxyFor/proxyIn swapping

lib/hydra/pcdm/models/concerns/object_behavior.rb, spec/hydra/pcdm/models/object_spec.rb
When plugging the recent changes into CurationConcerns, I discovered that I had been misreading the tests and confusing a stub Proxy class (which has a proxy_for method) for AF::Aggregation::Proxy (which has target and container methods).  This PR corrects the usage to use AF::Aggregation::Proxy#target.
Sorry for the churn on this.
=> Fixing foreign_key for ActiveFedora:Aggregation::Proxy

README.md
Noticed that the REAMDE install instructions say 0.4 but the gem's current version is 0.9.
I'm wondering if a note should be included with the AF guidance info also, from https://github.com/projecthydra/active_fedora:
```
ActiveFedora is a Ruby gem for creating and managing objects in the Fedora Repository Architecture (http://fedora-commons.org). ActiveFedora is loosely based on “ActiveRecord” in Rails. Version 9.0+ works with Fedora 4 and prior versions work on Fedora 3. Version 9.2+ works with Solr 4.10. Version 10.0+ works with Fedora >= 4.5.1.
```
=> update gem version in install instructions

.rubocop.yml, lib/hydra/pcdm/models/concerns/object_behavior.rb, lib/hydra/pcdm/models/concerns/pcdm_behavior.rb, lib/hydra/pcdm/object_indexer.rb, lib/hydra/pcdm/pcdm_indexer.rb, spec/hydra/pcdm/models/collection_spec.rb, spec/hydra/pcdm/object_indexer_spec.rb, spec/hydra/pcdm/pcdm_indexer_spec.rb
This PR allows for reversing the collection->sub-collection relationship. It leverages the work @escowles did (#227) for reversing the collection->object relationship by pulling the relavant code up from the object module into the pcdm module for model behavior and indexer.  This will increase the performance for collections with many sub-collections which may be more common in dSpace instances.
Future work could be allowing the object->object relationship to be reversed.  This could set the stage for a refactoring of the model behaviors and possibly other modules and classes in hydra-pcdm.
Resolves #243.
=> Provide tooling for reversing nested collection relationships

README.md
Particularly, links were broken for CI builds and badges.
=> Update README.md to reflect Samvera name

hydra-pcdm.gemspec
AF `12.0` will soon pin to Rails 5.1 - in the meantime we can get a
working release of 1.0 out by doing this.
Closes #251
=> Pin Rails to 5.1

hydra-pcdm.gemspec
Reverts samvera/hydra-pcdm#263
ActiveFedora 12.0.2 was released which pins to rails 5.1.  Removing this pin will allow `hydra-pcdm` to work with rails 5.2 once ActiveFedora 12.1.0 is released.
=> Revert "Pin Rails to 5.1"

README.md
Hydra-PCDM appears not to be using CodeClimate, so we should remove the badge.
If CodeClimate was set up, we would see builds here: https://codeclimate.com/github/samvera/hydra-pcdm/builds
Fixes #278
=> Removes CodeClimate badge

hydra-pcdm.gemspec
there's no need to specify this, and it is very very old.
=> remove outdated bundler dependency

.circleci/config.yml, hydra-pcdm.gemspec, spec/hydra/pcdm/models/file_spec.rb
Resolves #287 and also addresses the following:
- Updating the samvera/circleci-orb and bundler for CircleCI
- Removing CircleCI test suite executions for Ruby 2.4.z
- Updates the Ruby releases tested on CircleCI
- Updating the CircleCI executor to samvera/ruby_fcrepo_solr_redis_postgres and Solr core installation using samvera/install_solr_core
- Updating coveralls to coveralls_reborn
- Disabling the server-managed properties test in the suite for Hydra::PCDM::Models::File
=> Adding nightly CircleCI test suite executions

hydra-pcdm.gemspec
Relaxing this is necessary to allow bringing in a newer version of rdf-vocab.  Without this Hyrax was forced to bring in an earlier version of rdf-vocab which forced bringing in nokogumbo which is incompatible with ruby 3.2.
=> Allow newer versions of rdf-vocab
