spec/spec_helper.rb

This makes the build not fail on "You set RAILS_ENV" errors

Set the environment for testing

---

spec/spec_helper.rb

@jcoyne sorry, I accidentally deleted the branch which closed #35. I've updated it now.

Clean out jetty before each test

---

lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb

NOTE:
* Temporarily using branch activefedora-aggregation/FAIL_to_add_item to allow tests to pass.  Need to switch back to master when it is merged.
Pending Tests:
* unwritten tests are marked with xit
* tests using method << are marked with xit

Fix test failures

---

lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb

add tests for...
1) Hydra::PCDM::Object can aggregate (pcdm:hasMember) Hydra::PCDM::Object
4) Hydra::PCDM::Object can NOT aggregate Hydra::PCDM::Collection
5) Hydra::PCDM::Collection can NOT aggregate non-PCDM objects

add object tests

---

lib/hydra/pcdm/models/concerns/collection_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb

Addresses most of the collections behavior rules in #23, excepting points 5 and 6.

Enforce a collection's inclusion of objects and collections

---

Gemfile
hydra-pcdm.gemspec
spec/spec_helper.rb

It's wasted effort and prevents jruby from building

Don't install byebug on travis.

---

lib/hydra/pcdm.rb
lib/hydra/pcdm/indexer.rb
lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb

Solrize member ids in objects and collections

---

lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb

Remove the append (<<) operator from Collection and Object

---

lib/hydra/pcdm/models/concerns/object_behavior.rb
spec/hydra/pcdm/models/object_spec.rb
spec/spec_helper.rb

Just refactoring some things in the object spec I noticed while I was in there.

Refactor object spec.

---

spec/hydra/pcdm/services/collection/add_collection_spec.rb

changes to tests to improve execution time
* collapse first 4 tests into one that covers several use cases while avoiding duplicate setups
* for validation tests, create objects only once
* do not save unless absolutely necessary
* use new instead of create (effectively working with objects in memory as they are not saved to Fedora)
Impact:
* before - 24s
* after - 0.3s
This is almost exclusively accounted for by the use of new instead of create.
Please review closely as this will be used as a model for optimizing other tests.

optimize add_collection_spec test

---

lib/hydra/pcdm/services/collection/add_related_object.rb
spec/hydra/pcdm/services/collection/add_related_object_spec.rb
spec/hydra/pcdm/services/object/add_related_object_spec.rb

Also fix typo in raised error message for invalid parent_collection in AddRelatedObjectToCollection

optimize add_related_object tests for objects and collections

---

lib/hydra/pcdm/collection_indexer.rb
lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
lib/hydra/pcdm/object_indexer.rb
lib/hydra/pcdm/services/collection/get_objects.rb
lib/hydra/pcdm/services/object/get_objects.rb
spec/hydra/pcdm/collection_indexer_spec.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb
spec/hydra/pcdm/object_indexer_spec.rb
spec/hydra/pcdm/services/object/get_objects_spec.rb
spec/hydra/pcdm/services/object/remove_object_spec.rb

fixes https://github.com/projecthydra-labs/hydra-pcdm/issues/134

refactor to use consistent method names for getting parents and children

---

spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/services/collection/remove_collection_spec.rb
spec/hydra/pcdm/services/collection/remove_related_object_spec.rb
spec/hydra/pcdm/services/object/remove_object_spec.rb

Fixes #118 
* Reducing number of test objects created
* Using .new instead of .create where possible

Improving test performance

---

hydra-pcdm.gemspec

Update the activefedora-aggregation version in gemspec and remove patch level specification.

Use activefedora-aggregation ~> 0.3

---

lib/hydra/pcdm/services/collection/add_related_object.rb
lib/hydra/pcdm/services/collection/get_related_objects.rb
lib/hydra/pcdm/services/collection/remove_related_object.rb
lib/hydra/pcdm/services/object/add_related_object.rb
lib/hydra/pcdm/services/object/get_related_objects.rb
lib/hydra/pcdm/services/object/remove_related_object.rb

Partially addresses #146 (adds deprecations, actual removal to be done later)
* Scheduled for 7/31 along with other service removals

Deprecating related objects services

---

lib/hydra/pcdm/models/concerns/pcdm_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb

Validating related_objects are pcdm:Objects

---

spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/file_spec.rb
spec/hydra/pcdm/models/object_spec.rb

this was a very simple change.  It simply involved changing the following format in rspec files:
expect{ ... } to expect { ... }

change expect{ ... } to expect { ... }

---

Gemfile
README.md
Rakefile

Also, clean up the README and badgify it like other Hydra projects.

Add style-checking to the spec task.

---

spec/hydra/pcdm/models/collection_spec.rb

Cleaning up a couple of weird wording changes from #170

Fixing a few rubocop wording changes

---

lib/hydra/pcdm/models/concerns/pcdm_behavior.rb
spec/hydra/pcdm/models/collection_spec.rb

add method parent_collection_ids to models/concerns/pcdm_behavior.rb to return all the ids belonging to the parent collections, and add test case to
test this new method.

add method parent_collection_ids and tests for this method.

---

lib/hydra/pcdm/models/concerns/object_behavior.rb

Deleted the deprecated definition for contains=

Deleted contains def

---

lib/hydra/pcdm/models/concerns/pcdm_behavior.rb
lib/hydra/pcdm/validators/ancestor_validator.rb

move the functionality of checking for ancestory from ancestory_validator.rb to pcdm_behavior.rb

move ancestory check from ancestory_validator to pcdm_behavior

---

hydra-pcdm.gemspec
lib/hydra/pcdm/collection_indexer.rb
lib/hydra/pcdm/models/concerns/collection_behavior.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
lib/hydra/pcdm/models/concerns/pcdm_behavior.rb
lib/hydra/pcdm/object_indexer.rb
lib/hydra/pcdm/version.rb
spec/hydra/pcdm/collection_indexer_spec.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/file_spec.rb
spec/hydra/pcdm/models/object_spec.rb
spec/hydra/pcdm/object_indexer_spec.rb

Fix for issue https://github.com/projecthydra-labs/hydra-pcdm/issues/180

fix issue 180 - Rework association names. drop parent_ and child_

---

Gemfile
lib/hydra/pcdm/models/concerns/pcdm_behavior.rb

Use the IndirectContainer ids reader provded by ActiveFedora

---

lib/hydra/pcdm/models/concerns/object_behavior.rb
lib/hydra/pcdm/models/concerns/pcdm_behavior.rb
lib/hydra/pcdm/version.rb
spec/hydra/pcdm/models/collection_spec.rb
spec/hydra/pcdm/models/object_spec.rb
spec/hydra/pcdm_spec.rb

Previously it was returning all objects.

When the object isn't saved it shouldn't be a member of anything

---

spec/spec_helper.rb

Syncing coverage calculation with hydra-works

---

lib/hydra/pcdm/models/concerns/pcdm_behavior.rb

Also asking for a bit of knowledge in comments.

Removing duplication of knowledge

---

lib/hydra/pcdm/models/file.rb
spec/hydra/pcdm/models/file_spec.rb

Enable schemas on Hydra::PCDM::File to support projecthydra-labs/hydra-works#292

Add schemas to File

---

.gitignore
lib/hydra/pcdm.rb
lib/hydra/pcdm/collection_indexer.rb
lib/hydra/pcdm/config.rb
lib/hydra/pcdm/models/concerns/object_behavior.rb
lib/hydra/pcdm/object_indexer.rb
lib/hydra/pcdm/pcdm_indexer.rb
lib/hydra/pcdm/vocab/pcdm_terms.rb
spec/hydra/pcdm/models/object_spec.rb
spec/hydra/pcdm/object_indexer_spec.rb
spec/hydra/pcdm/pcdm_indexer_spec.rb

* Adding #member_of_collections for objects to link to collections they are members of
* Updating PCDM RDF vocab

Adding #member_of_collections

---

spec/hydra/pcdm/models/file_spec.rb

Refactor and repair technical metadata specs

---

.rubocop.yml
lib/hydra/pcdm/collection_indexer.rb
lib/hydra/pcdm/object_indexer.rb
lib/hydra/pcdm/pcdm_indexer.rb
spec/hydra/pcdm/collection_indexer_spec.rb
spec/hydra/pcdm/object_indexer_spec.rb
spec/hydra/pcdm/pcdm_indexer_spec.rb

This follows the pattern used by ActiveFedora.

generate_solr_document should yield the document

---

.rubocop.yml
lib/hydra/pcdm/collection_indexer.rb
lib/hydra/pcdm/object_indexer.rb
lib/hydra/pcdm/pcdm_indexer.rb
spec/hydra/pcdm/collection_indexer_spec.rb
spec/hydra/pcdm/object_indexer_spec.rb
spec/hydra/pcdm/pcdm_indexer_spec.rb

Reverts samvera/hydra-pcdm#240

Revert "generate_solr_document should yield the document"

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SUPPORT.md

- Resolve #254; Update contribution guidelines
- Resolve #255; Add contact info

Update docs to match templates

---

Gemfile

Update rubocop & rubocop-rspec gem

---

lib/hydra/pcdm/version.rb

Release version 1.0

---

.circleci/config.yml

Re: samvera/maintenance#20
Re: samvera/maintenance#21

Tidy up CircleCI Ruby and Rails versions

---

.circleci/config.yml
.rubocop.yml
Gemfile
hydra-pcdm.gemspec
spec/hydra/pcdm/models/file_spec.rb

Depends on unreleased branches of active-triples and active-fedora.

Support for ruby3 and rails 7

---

hydra-pcdm.gemspec
lib/hydra/pcdm/version.rb

These are the changes proposed by the Pull Request https://github.com/samvera/hydra-pcdm/pull/296, rebased in order to facilitate with the review and merging process:
- https://github.com/samvera/hydra-pcdm/pull/295
- https://github.com/samvera/hydra-pcdm/issues/289

Rebases the commits from the Pull Request #296

---

lib/hydra/pcdm/version.rb

Release 1.3.0

---

.circleci/config.yml
hydra-pcdm.gemspec
solr/conf/_rest_managed.json
solr/conf/admin-extra.html
solr/conf/elevate.xml
solr/conf/mapping-ISOLatin1Accent.txt
solr/conf/protwords.txt
solr/conf/schema.xml
solr/conf/scripts.conf
solr/conf/solrconfig.xml
solr/conf/spellings.txt
solr/conf/stopwords.txt
solr/conf/stopwords_en.txt
solr/conf/synonyms.txt
solr/conf/xslt/example.xsl
solr/conf/xslt/example_atom.xsl
solr/conf/xslt/example_rss.xsl
solr/conf/xslt/luke.xsl

Required re-doing the Solr and Fedora setup because something is wrong with the Solr core creation in the `samvera/install_solr_core`  orb.  This also required a local Solr configuration directory to pass into the core creation API; the configuration was taken directly from the one being used in [active_fedora](https://github.com/samvera/active_fedora/tree/main/lib/generators/active_fedora/config/solr/templates/solr/conf).

Testing for Ruby 3.3 and Rails 7.2
